Update and fix plugins. (#350)
* Fix plugin l4d2_setscores.smx

Fixes plugin 'l4d2_setscores.smx':
1) You can change points during voting, you need to execute the command again with your points. You can even be a spectator. 
2) If you enable the 'setscore_allow_player_vote' cvar, then the voting does not work for the admin if he is a spectator.

* Update l4d2_setscores.sp

* Fix builtinvotes crash

Fix builtinvotes, causing the server to crash. More information here -https://github.com/A1mDev/builtinvotes

* Fixed double voting

Fixed double voting

* update builtinvote.inc

update builtinvote.inc

* Update builtinvotes.inc

* Fix stagger bug

if you are shoved when you are on the ladder then you will not be able to move anymore until you are killed.

* Update builtinvotes, fix logs errors.

Update builtinvotes:
1) Improved code security
2) Fix of appearing errors in the logs

* boomer_horde_equalizer update

Added some functionality:
1) Added error output because it is not clear when it breaks
2) Fix offset

@Derpduck thx for help

* Retrun left4dhooks

Retrun left4dhooks

* Delete match_vote.smx

* Fix plugins after l4d2 update

Fix of offsets after the update, now it will dynamically find new offsets if possible, the rest will be in the gamedata 'l4d2_si_ability', and updating the syntax. It was hard to find it and fix it, and these are not all plugins requiring updating. Give me chocolate for that =))

* Forgot to remove

Removed test code.

* Fix plugins after update 2

Fix plugins after update 2

* Fix plugins after update 3

Fix plugins after l4d2 update 3

* Big plugins update:

1. si_fire_immunity -> called every time 'ExtinguishEntity(client)', if attacker == 0, i.e any object, not a player. Due to the fact that in the event the string 'weapon' is always empty. It also created a bunch of unnecessary timers with checks. For the reason that the event 'player_hurt' is very often called, this could affect performance to some extent. Add cvars 'infected_extinguish_time' and 'tank_extinguish_time', how long will it take for an infected or tank to be extinguished.
2. l4d_jockey_ledge_hang -> removed old code, new code works better.
3. l4d2_smoker_drag_damage_interval -> l4d2_smoker_drag_damage_interval_zone.smx, fixed incorrect work with game timer (CountdownTimer).
4. infected_flow_warp, it created variables without initialization, there was garbage from memory, and then tried to use, this could potentially break the server, the new method will work better. Besides, the old code worked badly, there was no sorting by distance. Now you can use the command !warpto without arguments, and you will be thrown to the farthest survivor, or use character names !warpto nick.
5. Fixed all compilation warnings except enum struct.
6. Fixed CTerrorPlayer offsets which can be found with, the rest are in gamedata 'l4d2_si_ability.txt'.
7. Add include 'l4d2_hybrid_scoremod.inc'.
8. Updated plugins syntax and include .
9. Fix include 'l4d2_util' plugins using it were compiled with unused variables.
10. Fixed wrong variable names, in my updated plugins.
11. Performance fixes.
12. Minor fixes.

* Fix l4d2_nosey_parker

1. Сode improvement
2. Fixed wrong work with ArrayStack, because of this, the plugin did not work
3. Removed double checks from include 'l4d2util'

* Fix plugins

1. Fix l4d2_jockey_skeet.smx there were many errors in the logs
2. Fix l4d2_hunter_no_deadstops.smx wrong check, my mistake.
3. Fix l4d2_notankautoaim.smx, after update (works for windows). Added error output if this stops working after update. Now, when the plugin is unloaded, everything will be returned as it was, which is important when unloading configs (bytes will be returned to the original ones).

* Minor fixes

Minor fixes

* Added windows offsets

All offsets were tested on a Windows server, maybe someone else needs it :D

* boomer_horde_equalizer support windows

Added windows support to plugin boomer_horde_equalizer.smx tested on windows and linux.

* Minor changes

Minor changes

* Fix si_fire_immunity

Fix si_fire_immunity

* Fix static spread on windows

Rena and I did a great job to fix this for windows. It took a long time to do this .. Thanks @Rena =)

* Small fix code_patcher

1. New syntax
2. Fix errors in logs:
: L 06/28/2021 - 22:26:20: [SM] Exception reported: Invalid index 1 (count: 1)
L 06/28/2021 - 22:26:20: [SM] Blaming: code_patcher.smx
L 06/28/2021 - 22:26:20: [SM] Call stack trace:
L 06/28/2021 - 22:26:20: [SM]   [0] GetArrayString
L 06/28/2021 - 22:26:20: [SM]   [1] Line 215, D:\SourcePawn10\code_patcher.sp::OnPluginEnd

* Update plugins & ext

1. Add latest version 'l4dtoolz' by @Accelerator74, bugs with 32 slots were found, now 31 slots are available, added earlier unlocking of slots before loading the map, some signature updates.
2. Add latest version 'builtinvotes' and update include.
3. Update include l4d2util , recompiling plugins using this. (Update method GetInfectedAbilityEntity, update syntax and minor fixes).
4. Update syntax l4d2_m2_control_eq and minor fixes
5. Fix compile with new syntax l4d_setscores

* Add l4d2_m2_control_eq.smx

1. Add l4d2_m2_control_eq.smx
2. Delete SI_Targeting.sp unused file from hardcoop

* Update plugins

1. Remove hardcode: offset zombitmanager will now be in gamedata l4d2_zombie_manager.txt
2. Fix l4d2_smoker_drag_damage_interval it didn't reset the timer tongue drag damage, if we use the first damage. This plugin is needed so that this timer does not depend on cvar 'tongue_choke_damage_interval', instead we use our 'tongue_drag_damage_interval'. This timer always resets back when dealing damage.
3. l4d2_uncommon_blocker correction of description.

* Fix l4d2_dominatorscontrol.smx on windows

Fix l4d2 dominator control.smx on windows, it seems that it has not worked for a long time, but has it ever worked?

* Update windows signature

Update windows signature

* l4d2utill fix warning

1. l4d2_nosey_parker.sp(34) : warning 201: redefinition of constant/macro (symbol "ARRAY_INDEX_TIMESTAMP")

* Add source file 'nosaferoomkits'

Add source file 'nosaferoomkits'

* Fix typo

Fix typo

* Fix static spread on windows

1. Fix static spread on windows
Noticed that on Linux, static spread still works incorrectly, even after changing the offset

* Fix visualise_impacts

Fix visualise_impacts, not working after loading the map, it was necessary to constantly reload it.

* Update current.sp

Remove decompiled code and update syntax

* Update l4d2_uniform_spit

1. Remove hardcode, the offset will now be in the gamedate. I also noticed that this offset is different in windows.
2. Update syntax
3. Minor fixes
4. bAltTick is now saved in the structure StringMap, and this array will not need to be reset after use

* Delete old include & gamedata

Delete old include & gamedata

* Update plugins

1. l4d2_si_staggers - removal of old and broken offsets, delete unnecessary gamedata 'l4d2_si_stagger.txt'
2. Small plugins improvements and update syntax

* Add l4d2_si_staggers.smx

Add l4d2_si_staggers.smx

* Fix l4d2_director_commonlimit_block

Fix l4d2_director_commonlimit_block, I don't think it will work without #include <left4dhooks>.

* Update l4d2_weaponrules

Update l4d2_weaponrules, fix warning 'warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs'.

Update l4d2_util_weapons.inc

* Update l4d2_weaponrules

Update l4d2_weaponrules

* Update pill_passer

Update pill_passer

* Update l4d2_pickup

Update l4d2_pickup

* Update l4d2_blind_infected

1. Update l4d2_blind_infected
2. Remove unused include weapons.inc

* Update TickrateFixes, lerpmonitor, l4d_bash_kills

Update 'TickrateFixes':
1. Fix warning 'warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs'.
2. Update syntax

Fix 'lerpmonitor':
1. fixed my mistake, it turns out that the array was cleared every time the player exited, this should not be
2. Remove include 'readyup.inc' and unnecessary forward 'OnRoundIsLive'

Update 'l4d_bash_kills':
1. improved readability

* Update pause

Update pause

* Update l4d2_playstats

Update l4d2_playstats

* Update ratemonitor

Update ratemonitor

* Update 'pause'.

Update 'pause'.

* Update l4d2_playstats

Update l4d2_playstats

* Add support sm1.11

Add support sm1.11

* Remove unnecessary

Remove unnecessary

* Update plugins

1. Removing unsafe macros
2. Add support sourcemod 1.11

* Update plugins & includes

Update l4d2_spitblock:
1) Update syntax
2) Improved performance (Added bool 'IsBlockEnable' to SDKHook OnTakeDamage now the plugin will not load the server if the map is not added to the block).

Fix lerpmonitor:
1. Fix typo 'NM_GetLerpTime'
Thanks @Forgetest

Update and fix l4d2util.inc
Thanks @Forgetest:

Update l4d2_uniform_spit:
1. Minor changes

* Minor changes

Minor changes

* Update l4d2utill.inc

Update l4d2utill.inc

* Fix plugin visualise_impacts

Fix plugin visualise_impacts:
1. It was impossible to show the client more than 15 impacts, now this has been fixed.

* Fix static spread on linux

Fixed static distribution patch for linux. Rena and i worked on this again and fixed it, thanks to Rena! =)

* Update plugin visualise_impacts

Update plugin visualise_impacts. Thanks
ChocolateCat.

* Update l4d2util_constants.inc

* Update plugins

1. Update l4d2_antibaiter:
	Added error output if the plugin does not find the gamedata or address or offset.
	The old code was bad, which is not clear when the plugin doesn't work.
	This plugin is also detached from other plugins and works independently of them (readyup and pause).
	Also, the plugin stops working after the round is over.
	Tested work on Linux and windows.
	Removed the hardcore code, now the offset is in the new gamedate l4d2_cdirector.txt.

2. Added support for old versions of sourcemod in some plugins.
3. Fixed incorrect code related to enum.
4. l4d2util - added several functions.

* Remove unnecessary

Remove unnecessary

* Fix plugin temphealthfix

Fixed incorrect work with strings.

* Fix crash UTIL_SETMODEL.

The problem was that it was impossible to set the model without the model folder.
Example: 'models/w_models/weapons/w_smg_uzi.mdl'.
Old include didn’t set any model, there was an empty line, so we didn’t face this problem.
Apparently the game was set by the model itself.
I think there could be problems of course with old include, for example, an invisible weapon.
Example of how OLD include works: - https://github.com/SirPlease/L4D2-Competitive-Rework/blob/8a0407c27f84e185031be9ea02675b255ff2d142/addons/sourcemod/scripting/include/weapons.inc#L395 .

* Remove unnecessary

Remove unnecessary

* l4d2util removed double check

l4d2util removed double check

* Update plugins again.

Update include 'l4d2util.inc':
1. Fixed order 'SurvivorCharacter'.
2. Added several functions.

Update 'double_getup' & 'l4d2_getup_slide_fix' & 'l4d2_getupfix':
1. Fixed the order of the characters in accordance with the new include 'l4d2util'.
2. Code improvements & minor fixes.
3. Fixed double checks due to fix include 'l4d2util.inc'
4. Update syntax.
5. Changes have been tested, plugins work correctly after inclusion changes, the change was related to the order of the survivors characters.

Fix 'l4d2_playstats':
1. Fixed incorrect console output

* Update 'l4d2_collision_adjustments':

1. Removed extra code that was supposed to fix a bug in the game. This problem was fixed by the game developers after updates.
2. Update syntax.
3. Fixed function return value for valid objects.

* Update l4d2_uniform_spit

1. Add support for older version sourcemod
2. Minor fixes

* Update l4d2_blind_infected.

1. Add support for older version sourcemod.
2. Minor fixes.

* Update 'TickrateFixes'

1. Add support for older version sourcemod.
2. Minor fixes.

* Update 'l4d_weapon_limits'

1. Add support for older version sourcemod.
2. Minor fixes.

* Update 'ratemonitor'.

1. Add support for older version sourcemod.
2. Minor fixes.

* Update plugins.

1. Add support for older version sourcemod.
2. 'spechud' removed broken code

* Fix 'l4d_weapon_limits'

1. Fixed incorrect check in the plugin.

* Add l4d_weapon_limtis.smx

Add l4d_weapon_limtis.smx

* Update 'l4d2_bw_rock_hit'.

1. Add support windows
2. Update syntax
3. Added error output if plugin does not find signature or gamedata.
4. Removed unnecessary checks added code optimization.

* Update 'l4d_tankpunchstuckfix'.

1. Add support windows.
2. Update syntax.
3. Added error output if plugin does not find signature or gamedata.
4. Removed unnecessary checks added code optimization.

* Fix crash UTIL_SetModel another one.

Fixed another crash related to another problem.
In plugins l4d2_tank_props_glow or l4d2_tank_support the buffer size was too small to get the model,
so we were getting a crash if the full path and model name were greater than the length of the string.

Increased string length in other plugins working with netprop 'm_ModelName'.

Thanks @shqke for finding these problems!

* Update and fix 'l4d2_weapon_attributes'.

1. Fixed problematic code due to which it was possible to set 1 attribute for 1 weapon. Thanks @SirPlease for reporting a problem.
2. Fixed an issue due to which it was impossible to use the correct name of the weapon, with the prefix "weapon_". Example:  'sm_weapon weapon_smg_silenced rangemod 0.80'. In this case, the plugin made a double prefix.
3. Added error output to sourcemod logs if you use the wrong attribute or weapon name.
4. Completely rewritten code that works with resetting weapons attributes to vanilla values.
5. Added optimization to the code OnTakeDamage, reduced server load if you don't use the attribute 'tankdamagemult', unnecessary code won't work. Also added a check for the type of damage, the code only works for the type of damage 'DMG_BULLET'.
6. Added console command for server 'sm_weapon_attributes_reset', which will reset all weapon attributes to their default value.
7. Added cvar 'sm_weapon_hide_attributes', this console command allows to change how the variable works 'sm_weapon_attributes', which should show the attributes of the weapon. 0 disable console command, 1 - show weapon attributes only to admin, 2 - show weapon attributes to everyone>
8. Update syntax.

* Fix wrong include

Fix wrong include

* Fix typo

Fix typo

* Update includes

Update includes

* Small plugins change

Update 'despawn_health':
1. Minor fixes.
2. Update syntax.

Update 'musical_jockeys'.
1. Update syntax.
2. Removed unnecessary checks.
3. Removed unnecessary include.

* Add the latest version 'FollowTarget_Detour'.

ChangeLog:
v1.2 (12-Mar-2021)
- Fixed frozen camera (thanks to tRololo312312).

v1.1 (27-Nov-2020)
- Added windows signatures
- debug mode is turned off
- hardcoded camera struct index moved to a gamedata

* Nothing interesting

Nothing interesting

* Add windows support 'l4d2_lagcomp_manager'.

1. Plugin tested on platforms windows and linux.
2. Added the ability to debug the plugin.
3. Added warning if cvar 'sv_unlag' is disabled, since it can only work with this cvar.

* Update 'l4d2_ultra_witch'.

1. Add windows support.
2. Add gamedata and error output if plugin doesn't find signature or gamedata.
4. Add some code optimization.
5. Update syntax.
6. Added support for witch bride.

The plugin has been tested on Windows and Linux platforms.

* Fix gamedata 'l4d2_lagcomp_manager.txt'.

 Thanks @jensewe.

* Update 'l4d2_weapon_attributes'.

1. 'sm_weapon' command for the "tankdamagemult" attribute with a negative or zero value resets the attribute for the weapon specified in the command. Example: sm_weapon tankdamagemult weapon_smg -1.0;
2. 'sm_weapon_attributes_reset' command now also resets the attribute 'tankdamagemult' for all weapons.

* Fix 'l4d2_saferoom_detect'.

1. Fixed dependent plugins could not find this plugin.

* Compiling modified plugins.

Compiling modified plugins.

* Fix 'ratemonitor'.

1. I made several mistakes, so the plugin did not work correctly, now this has been fixed.

* Fix 'si_fire_immunity'.

1. Fixed an incorrect check that caused the plugin to work incorrectly.
2. Minor code improvements.

* Fixing and updating plugins.

1. Fixed compilation of some plugins.
2. 'l4d2_explosiondmg_prev' code optimization and update syntax.

* Fix the issue #348

Fix the issue #348